#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RGBPi.Android.Resource", IsApplication=true)]

namespace RGBPi.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public const int MvxBind = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int MvxDropDownItemTemplate = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int MvxItemTemplate = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int MvxLang = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int MvxSource = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int MvxTemplate = 2130771983;
			
			// aapt resource value: 0x7f010009
			public const int bar_corner_radius = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int bar_length = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int bar_orientation_horizontal = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int bar_pointer_halo_radius = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int bar_pointer_radius = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int bar_thickness = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int color_center_halo_radius = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int color_center_radius = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int color_center_show_old_color = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int color_pointer_halo_radius = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int color_pointer_radius = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int color_wheel_radius = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int color_wheel_thickness = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int bar_length = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int bar_pointer_halo_radius = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int bar_pointer_radius = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int bar_thickness = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int color_center_halo_radius = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int color_center_radius = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int color_pointer_halo_radius = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int color_pointer_radius = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int color_wheel_radius = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int color_wheel_thickness = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int colorPicker = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int svBar = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ColorChooserView = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int bar_corner_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorBars = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 2
			public const int ColorBars_bar_corner_radius = 2;
			
			// aapt resource value: 1
			public const int ColorBars_bar_length = 1;
			
			// aapt resource value: 5
			public const int ColorBars_bar_orientation_horizontal = 5;
			
			// aapt resource value: 4
			public const int ColorBars_bar_pointer_halo_radius = 4;
			
			// aapt resource value: 3
			public const int ColorBars_bar_pointer_radius = 3;
			
			// aapt resource value: 0
			public const int ColorBars_bar_thickness = 0;
			
			public static int[] ColorPicker = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 4
			public const int ColorPicker_color_center_halo_radius = 4;
			
			// aapt resource value: 3
			public const int ColorPicker_color_center_radius = 3;
			
			// aapt resource value: 2
			public const int ColorPicker_color_center_show_old_color = 2;
			
			// aapt resource value: 6
			public const int ColorPicker_color_pointer_halo_radius = 6;
			
			// aapt resource value: 5
			public const int ColorPicker_color_pointer_radius = 5;
			
			// aapt resource value: 0
			public const int ColorPicker_color_wheel_radius = 0;
			
			// aapt resource value: 1
			public const int ColorPicker_color_wheel_thickness = 1;
			
			public static int[] MvxBinding = new int[] {
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771983};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771986};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
